"""empty message

Revision ID: 89c1cfa36526
Revises: 
Create Date: 2018-10-09 15:33:37.465000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89c1cfa36526'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('about_me', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('name', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('telephone', sa.String(length=64), nullable=True))
    op.create_unique_constraint(None, 'users', ['telephone'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'telephone')
    op.drop_column('users', 'name')
    op.drop_column('users', 'about_me')
    # ### end Alembic commands ###
